#!/bin/bash

# Get list partition and disks
rm -f /tmp/photorec.listdisks
for disk in /dev/sd*[a-z]; do
	echo $disk >> /tmp/photorec.listdisks
	blkid $disk >> /tmp/photorec.listdisks
done

# Main dialog

TXT="Choose a disk..."

RET=$(cat /tmp/photorec.listdisks | yad --notebook --width=450 --height=250 --center --title="Photorec Launcher" --text="$TXT" --button=gtk-ok --button=gtk-close --list --column="Disk" --column="Details")
REL=$?

if [ $REL -eq 1 ]; then exit; fi

if [ -z "${RET}" ]; then
	TXT="Please select a disk!"
	yad --width=300 --center --title="Photorec Launcher" --text="$TXT" --button=gtk-close:0
	photorec_launcher &
	exit
fi

if [ $REL -eq 0 ]; then lxterminal -e "photorec ${RET%%|*}"; fi

rm -f /tmp/photorec.listdisks
