#!/bin/bash

# Get list of disk
rm -f /tmp/safeaccess.listdisks
for disk in /dev/sd*[a-z]; do
	echo $disk >> /tmp/safeaccess.listdisks
	blkid $disk >> /tmp/safeaccess.listdisks
done

# Main dialog

TXT="Choose a disk to inspect STATUS, set RW or RO..."

RET=$(cat /tmp/safeaccess.listdisks | \
	yad --width=450 --height=250 --center --title="SafeAccess Manager" \
	--text="$TXT" --button="STATUS":2 --button="RW":6 --button="RO":4 --button=gtk-close:0 \
	--list --column="Disk" --column="Details")
REL=$?
BLOCKDEVPATH=${RET%%|*}
BLOCKDEV=${BLOCKDEVPATH##*/}

if [ $REL -eq 0 ]; then exit; fi

if [[ -z "${BLOCKDEV}" && -z "${BLOCKDEVPATH}" ]]; then
	TXT="Please select a disk!"
	yad --width=300 --center --title="SafeAccess Manager" --text="$TXT" --button=gtk-close:0
	rm -f /tmp/safeaccess.listdisks
	safeaccess_manager &
	exit
fi

if [ "$(cat /sys/block/$BLOCKDEV/ro)" = "1" ]; then LOCKED=1; else LOCKED=0; fi

case $REL in
	2)
		case $LOCKED in
			1) TXT="$BLOCKDEV is on Read-only!" ;;
			0) TXT="$BLOCKDEV is on Read-Write!" ;;
		esac
		yad --width=300 --center --title="SafeAccess Manager" --text="$TXT" --button=gtk-close:0
		rm -f /tmp/safeaccess.listdisks
		safeaccess_manager &
		exit
	;;
	6)
		case $LOCKED in
			1)
				sync
				umount -l /mnt/$BLOCKDEV
				wrtblk-disable $BLOCKDEV
				REL=$?
				if [ $REL -eq 0 ]; then TXT="Successful!"; else TXT="Failed! - Check wrtblk command."; fi
				yad --width=300 --center --title="SafeAccess Manager" --text="$TXT" --button=gtk-close:0
				rm -f /tmp/safeaccess.listdisks
				safeaccess_manager &
				exit
			;;
			0)
				TXT="$BLOCKDEV is already in Read-Write!"
				yad --width=300 --center --title="SafeAccess Manager" --text="$TXT" --button=gtk-close:0
				rm -f /tmp/safeaccess.listdisks
				safeaccess_manager &
				exit
			;;
		esac
	;;
	4)
		case $LOCKED in
			1)
				TXT="$BLOCKDEV is already in Read-only!"
				yad --width=300 --center --title="SafeAccess Manager" --text="$TXT" --button=gtk-close:0
				rm -f /tmp/safeaccess.listdisks
				safeaccess_manager &
				exit
			;;
			0)
				sync
				umount -l /mnt/$BLOCKDEV
				wrtblk $BLOCKDEV
				REL=$?
				if [ $REL -eq 0 ]; then TXT="Successful!"; else TXT="Failed! - Check wrtblk command."; fi
				yad --width=300 --center --title="SafeAccess Manager" --text="$TXT" --button=gtk-close:0
				rm -f /tmp/safeaccess.listdisks
				safeaccess_manager &
				exit
			;;
		esac
	;;
esac

rm -f /tmp/safeaccess.listdisks
