#!/bin/bash
#toolbox gui

. /etc/DISTRO_SPECS

KEY=$RANDOM

# Run (fix gui/console program when launching)
run_cmd() {
	cd $HOME
	"$1"
}
export -f run_cmd

# HDD Tools
menu_hdd() {
	RET="testdisk_launcher\n"
	RET+="Testdisk\n"
	RET+="(Data Recovery) Recover lost partitions or corrupted filesystems.\n"
	RET+="photorec_launcher\n"
	RET+="PhotoRec\n"
	RET+="(Data Recovery) Recover lost files from hard disk and CD-ROM.\n"
	RET+="whdd_launcher\n"
	RET+="Whdd\n"
	RET+="(Data Recovery) HDD diagnostic and data recovery tool for Linux.\n"	
	RET+="gparted\n"
	RET+="GParted\n"
	RET+="(Partition) GUI-Based GNU parted.\n"
	RET+="fdisk_launcher\n"
	RET+="Fdisk\n"
	RET+="(Partition) Console-based partitioner.\n"
	RET+="gsmartcontrol\n"
	RET+="GSmartControl\n"
	RET+="(Diagnostic) Inspect drive and control S.M.A.R.T information.\n"
	RET+="bonnie_launcher\n"
	RET+="Bonnie++\n"
	RET+="(Benchmark) Disk and filesystem bechmarking tool.\n"
	RET+="iozone_launcher\n"
	RET+="IOzone\n"
	RET+="(Benchmark) Filesystem benchmark tool.\n"
	RET+="fio_launcher\n"
	RET+="Fio\n"
	RET+="(Benchmark) Flexible I/O tester.\n"
	RET+="nwipe_launcher\n"
	RET+="Nwipe\n"
	RET+="(Destroy) DBAN for Linux.\n"
	RET+="ssderaser\n"
	RET+="SSDeraser\n"
	RET+="(Destroy) SSD secure wipe. (NOT FOR HDD)\n"
	echo -e $RET
}
export -f menu_hdd
menu_hdd |\
    yad --plug=$KEY --tabnum=1 \
        --list --column="Command" --column="Name" --column="Description" --dclick-action='bash -c "run_cmd %s"' &

# OS Maintenance
menu_main() {
	RET="linuxchroot\n"
	RET+="LinuxChroot\n"
	RET+="(Linux) Chroot rescue\n"
	RET+="winreset\n"
	RET+="WinReset\n"
	RET+="(Windows) Reset Windows password (chntpw front-end)"
	echo -e $RET
}
export -f menu_main
menu_main |\
    yad --plug=$KEY --tabnum=2 \
        --list --column="Command" --column="Name" --column="Description" --dclick-action='bash -c "run_cmd %s"' &

# Boot Tools
menu_boot() {
	RET="bootbk\n"
	RET+="BootBk\n"
	RET+="(Boot) Backup and Restore MBR\n"
	echo -e $RET
}
export -f menu_boot
menu_boot |\
    yad --plug=$KEY --tabnum=3 \
        --list --column="Command" --column="Name" --column="Description" --dclick-action='bash -c "run_cmd %s"' &

# SYS Diagnostic
menu_sys() {
	RET="hardinfo\n"
	RET+="HardInfo\n"
	RET+="(Information/Benchmark) Inspect system information.\n"
	echo -e $RET
}
export -f menu_sys
menu_sys |\
    yad --plug=$KEY --tabnum=4 \
        --list --column="Command" --column="Name" --column="Description" --dclick-action='bash -c "run_cmd %s"' &

# NET Tools
menu_net() {
	RET="firefox-esr\n"
	RET+="Firefox ESR\n"
	RET+="(Web browser) Mozilla Firefox Browser.\n"
	RET+="ipinfo\n"
	RET+="IPInfo\n"
	RET+="(Information) Inspect network information.\n"
	echo -e $RET
}
export -f menu_net
menu_net |\
    yad --plug=$KEY --tabnum=5 \
        --list --column="Command" --column="Name" --column="Description" --dclick-action='bash -c "run_cmd %s"' &

# Other
menu_other() {
	RET="lxterminal\n"
	RET+="LXTerminal\n"
	RET+="(Terminal) LXDE Terminal.\n"
	echo -e $RET
}
export -f menu_other
menu_other |\
    yad --plug=$KEY --tabnum=6 \
        --list --column="Command" --column="Name" --column="Description" --dclick-action='bash -c "run_cmd %s"' &

# About
yad --plug=$KEY --tabnum=7 \
        --text-info < /etc/about &

# Main Dialog
TXT="\\t<b>Welcome!</b>\\n\\n"
TXT+="\\tYou're now running ${DISTRO_NAME} ${DISTRO_VERSION}\\n"
TXT+="\\tKernel: $(uname -sr)\\n\\n"
TXT+="\\tDouble-click selected tool to launch!\\n"

yad --notebook --width=890 --height=500 --center --title="RescuePup - Toolbox" --text="$TXT" --button=gtk-close --key=$KEY \
	--tab="HDD Tools" \
	--tab="OS Maintenance" \
	--tab="Boot Tools" \
	--tab="SYS Diagnostic" \
	--tab="NET Tools" \
	--tab="Others" \
	--tab="About" \
	--active-tab=${1:-1}
