name: debian-bookworm

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            compat-distro-version: bookworm64
          - arch: x86
            compat-distro-version: bookworm
    if: github.repository == 'rescuepuplinux/woof-CE'
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: ${{ matrix.arch }}
      compat-distro: debian
      compat-distro-version: ${{ matrix.compat-distro-version }}
      kernel: 5.15.x
      artifact: debian-${{ matrix.compat-distro-version }}-${{ github.run_number }}
      retention: 30
